import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function generateVariationWithAI(dna) {
  try {
    const prompt = `
You are a professional music producer.

Take this track DNA and create a new variation.

Rules:
- Keep the same general style
- Change groove, energy, structure and musical feel
- Make it interesting and usable for production
- Do NOT copy values exactly

Return ONLY valid JSON in this format:
{
  "newDNA": {...},
  "production_prompt": "text",
  "similarity_score": 0.0
}

DNA:
${JSON.stringify(dna, null, 2)}
`;

    const response = await openai.responses.create({
      model: "gpt-4.1-mini",
      input: prompt,
    });

    const text = response.output[0].content[0].text;

    const parsed = JSON.parse(text);

    return {
      newDNA: parsed.newDNA || dna,
      production_prompt: parsed.production_prompt || "Generated by AI",
      similarity_score: parsed.similarity_score || 0.5,
    };

  } catch (err) {
    console.error("OpenAI Error:", err.message);

    return {
      newDNA: dna,
      production_prompt: "AI failed",
      similarity_score: "0"
    };
  }
}

/**
 * חשוב מאוד!
 * זה מה שפותר את השגיאה שלך:
 * export בשם generateVariation
 */
export const generateVariation = generateVariationWithAI;
